# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likeBook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='of_user',
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='likeBook.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_books', to='likeBook.User'),
        ),
    ]
