# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
